import Foundation
import Testing
@testable import MacSpoonsTweaksKit

@Suite("SnippetGenerator")
struct SnippetGeneratorTests {

    // Pinned timestamp so golden-string comparisons are stable.
    private let fixedDate = ISO8601DateFormatter().date(
        from: "2026-06-08T12:34:56Z")!

    // MARK: - Headers and scaffolding

    @Test
    func emptyStateProducesHeaderOnly() {
        let snippet = SnippetGenerator.generate(
            state: AppState(),
            catalog: [:], repos: [:],
            timestamp: fixedDate)
        #expect(snippet.contains(SnippetGenerator.managedMarker))
        #expect(snippet.contains("Generated by MacSpoonsTweaks at 2026-06-08T12:34:56Z"))
        #expect(snippet.contains("require(\"mac_spoons_tweaks\")"))
        #expect(snippet.contains("hs.loadSpoon(\"SpoonInstall\")"))
        #expect(snippet.contains("-- No Spoons enabled."))
        #expect(!snippet.contains(":andUse("))
    }

    @Test
    func disabledSpoonsAreSkipped() {
        var state = AppState()
        // Enabled but NOT yet installed: still emit. `andUse` installs
        // on demand from Hammerspoon start, so the user's Apply
        // before-installation is honored.
        state.spoons["AndUseHandlesIt"] = SpoonState(
            sourceID: "catokolas", enabled: true, installedRef: nil)
        // Disabled → skip regardless of install state.
        state.spoons["Disabled"] = SpoonState(
            sourceID: "catokolas", enabled: false,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["AndUseHandlesIt": entry("AndUseHandlesIt"),
                      "Disabled":        entry("Disabled")],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(":andUse(\"AndUseHandlesIt\""),
                "enabled-but-uninstalled Spoons still get an andUse block")
        #expect(!snippet.contains("Disabled"))
    }

    @Test
    func spoonMissingFromCatalogIsSkippedRatherThanCrashing() {
        // State references a Spoon we don't have a catalog entry for —
        // typically a stale state.json after a catalog removal. Snippet
        // generation must not crash or produce broken Lua.
        var state = AppState()
        state.spoons["Ghost"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state, catalog: [:], repos: [:],
            timestamp: fixedDate)
        #expect(!snippet.contains("Ghost"))
    }

    // MARK: - andUse shape: catokolas (hasConfigure) Spoon

    @Test
    func catokolasSpoonWithConfigureUsesFnDeepMergePattern() {
        let entry = entry(
            "FocusFollowsMouse",
            hasConfigure: true, hasStart: true,
            hotkeyActions: ["toggle"])
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"),
            config: [
                "delay": .number(0.05),
                "excludedApps": .stringList(["Notification Center"]),
            ],
            hotkeys: ["toggle": HotkeyBinding(mods: ["ctrl","cmd"], key: "f")])

        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)

        // The repo registration block appears once, with all fields.
        #expect(snippet.contains("spoon.SpoonInstall.repos[\"catokolas\"]"))
        #expect(snippet.contains("url = \"https://github.com/catokolas/HS_SpoonsContrib\""))
        #expect(snippet.contains("branch = \"main\""))

        // andUse block — fn = function(s) s:configure({...}) end form.
        #expect(snippet.contains(":andUse(\"FocusFollowsMouse\", {"))
        #expect(snippet.contains("repo = \"catokolas\","))
        #expect(snippet.contains(
            "fn = function(s) s:configure({ delay = 0.05, " +
            "excludedApps = { \"Notification Center\" } }) end,"))
        #expect(snippet.contains(
            "hotkeys = { toggle = { { \"ctrl\", \"cmd\" }, \"f\" } },"))
        #expect(snippet.contains("start = true,"))
    }

    // MARK: - andUse shape: upstream (no :configure) Spoon

    @Test
    func upstreamSpoonWithoutConfigureUsesFlatConfigForm() {
        let entry = entry(
            "Caffeine",
            hasConfigure: false, hasStart: true,
            hotkeyActions: ["toggle"])
        var state = AppState()
        state.spoons["Caffeine"] = SpoonState(
            sourceID: "hammerspoon-official",
            enabled: true,
            installedRef: .zipETag(value: "W/\"abc\"", fetchedAt: fixedDate),
            config: ["show_notifications": .bool(true)],
            hotkeys: ["toggle":
                HotkeyBinding(mods: ["ctrl","alt","cmd"], key: "k")])

        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["Caffeine": entry],
            // sourceID is "hammerspoon-official", but repos[sourceID] = .default
            // means SpoonInstall's built-in "default" is used and we don't
            // emit a registration.
            repos: ["hammerspoon-official": .default],
            timestamp: fixedDate)

        // No repo registration for default.
        #expect(!snippet.contains("spoon.SpoonInstall.repos["))
        // Flat config form (no fn wrapper). The andUse block emits the
        // SpoonInstall repo NAME ("default"), not the catalog source
        // id ("hammerspoon-official") — that's the only string
        // spoon.SpoonInstall.repos knows about for upstream Spoons.
        #expect(snippet.contains("repo = \"default\","))
        #expect(!snippet.contains("repo = \"hammerspoon-official\","))
        #expect(snippet.contains("config = { show_notifications = true },"))
        #expect(!snippet.contains("fn = function"))
        #expect(snippet.contains("start = true,"))
    }

    // MARK: - Nesting

    @Test
    func deeplyNestedConfigSurvivesEncoding() {
        // Matches the MouseTrackpadTweaks shape — the worst case for
        // the recursive encoder, and the failure mode the deep-merge
        // (`fn` form) was designed to avoid: changing one nested key
        // must leave its siblings untouched on the Spoon side.
        let entry = entry(
            "MouseTrackpadTweaks",
            hasConfigure: true, hasStart: true,
            hotkeyActions: ["toggle"])
        var state = AppState()
        state.spoons["MouseTrackpadTweaks"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"),
            config: ["middleClick": .object([
                "multiFinger": .object([
                    "fingerCount": .int(4),
                ]),
            ])])

        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["MouseTrackpadTweaks": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)

        #expect(snippet.contains(
            "fn = function(s) s:configure({ " +
            "middleClick = { multiFinger = { fingerCount = 4 } } " +
            "}) end,"))
    }

    // MARK: - Edge cases

    @Test
    func startEmittedOnlyIfLifecycleHasStart() {
        // MoveSpaces — hasStart=false — should NOT emit start = true.
        let entry = entry(
            "MoveSpaces",
            hasConfigure: false, hasStart: false,
            hotkeyActions: ["space_left", "space_right"])
        var state = AppState()
        state.spoons["MoveSpaces"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"),
            hotkeys: ["space_left":
                HotkeyBinding(mods: ["shift","ctrl"], key: "left")])
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["MoveSpaces": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(!snippet.contains("start = true"))
        #expect(snippet.contains("hotkeys = { space_left = "))
    }

    @Test
    func pausedSpoonOmitsStartTrue() {
        // hasStart=true + paused=true → andUse block still emitted (so
        // config / hotkeys / load survive a reload), but no `start = true`.
        let e = entry(
            "FocusFollowsMouse",
            hasConfigure: true, hasStart: true,
            hotkeyActions: ["toggle"])
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas",
            enabled:  true,
            paused:   true,
            installedRef: .gitCommit("abc"),
            config:   ["delay": .number(0.05)],
            hotkeys:  ["toggle":
                HotkeyBinding(mods: ["ctrl","cmd"], key: "f")])
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": e],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(":andUse(\"FocusFollowsMouse\""))
        #expect(snippet.contains(":configure({"))
        #expect(snippet.contains("hotkeys = { toggle = "))
        #expect(!snippet.contains("start = true"))
    }

    @Test
    func emptyConfigAndHotkeysProducesMinimalBlock() {
        // A user could enable a Spoon, install it, but leave defaults.
        let entry = entry(
            "Bare", hasConfigure: true, hasStart: true, hotkeyActions: [])
        var state = AppState()
        state.spoons["Bare"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["Bare": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(":andUse(\"Bare\", {"))
        #expect(!snippet.contains("fn = function"))
        #expect(!snippet.contains("config = "))
        #expect(!snippet.contains("hotkeys = "))
        #expect(snippet.contains("start = true,"))
    }

    @Test
    func manifestHotkeyDefaultsRenderEvenWithoutUserOverrides() {
        // Regression: when state.hotkeys is empty but the manifest
        // declared a `default` for an action, the snippet must still
        // emit `hotkeys = { ... }` so SpoonInstall:andUse binds it.
        // Without this, `spoon.X:bindHotkeys` is never called and the
        // chord doesn't fire — exactly the bug a pre-v0.2.0 install
        // hits after upgrading.
        let entry = entry(
            "FocusFollowsMouse",
            hasConfigure: true,
            hasStart: true,
            hotkeyDefaults: [("toggle",
                HotkeyBinding(mods: ["shift", "ctrl", "cmd"], key: "f"))])
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(
            "hotkeys = { toggle = { { \"shift\", \"ctrl\", \"cmd\" }, \"f\" } },"))
    }

    @Test
    func userOverrideWinsOverManifestDefault() {
        // If the user recorded an explicit override, the resolve step
        // must not silently overwrite it with the manifest default.
        let entry = entry(
            "FocusFollowsMouse",
            hasConfigure: true,
            hasStart: true,
            hotkeyDefaults: [("toggle",
                HotkeyBinding(mods: ["shift", "ctrl", "cmd"], key: "f"))])
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas",
            enabled: true,
            installedRef: .gitCommit("abc"),
            hotkeys: [
                "toggle": HotkeyBinding(mods: ["cmd"], key: "g"),
            ])
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": entry],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(
            "hotkeys = { toggle = { { \"cmd\" }, \"g\" } },"))
        #expect(!snippet.contains("\"f\" }"))
    }

    // MARK: - Activate hotkey

    @Test
    func activateHotkeyEmitsBindBlockAndSkipsAndUseHotkeys() {
        // Spoon with an activateHotkey: snippet must NOT emit
        // `hotkeys = { … }` in the andUse block (SpoonInstall doesn't
        // own the chord any more) AND must emit a `hs.hotkey.bind`
        // block that closes over `mstActive` + alert + override
        // persistence.
        var e = entry("FocusFollowsMouse",
                      hasConfigure: true, hasStart: true,
                      hotkeyActions: [])
        e.activateHotkey = HotkeyBinding(
            mods: ["shift", "ctrl", "cmd"], key: "f")
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": e],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        // No hotkeys = block in the andUse.
        let andUseRange = snippet.range(of: ":andUse(\"FocusFollowsMouse\"")!
        let afterAndUse = snippet[andUseRange.lowerBound...]
        let andUseEnd = afterAndUse.range(of: "})")!.upperBound
        let andUseBody = afterAndUse[..<andUseEnd]
        #expect(!andUseBody.contains("hotkeys = "))
        // The activate-hotkey block follows.
        #expect(snippet.contains("-- Activate hotkey: FocusFollowsMouse"))
        #expect(snippet.contains(
            "hs.hotkey.bind({ \"shift\", \"ctrl\", \"cmd\" }, \"f\""))
        #expect(snippet.contains("mstActive[\"FocusFollowsMouse\"] = true"))
        #expect(snippet.contains("mstSetOverride"))
        #expect(snippet.contains("hs.alert.show"))
        // Plus the runtime-override applier at the bottom.
        #expect(snippet.contains("mac_spoons_tweaks_overrides.lua"))
        #expect(snippet.contains("hs.timer.doAfter"))
    }

    @Test
    func activateHotkeyHonoursUserOverride() {
        // state.activateHotkeyOverride wins over manifest default.
        var e = entry("FocusFollowsMouse",
                      hasConfigure: true, hasStart: true,
                      hotkeyActions: [])
        e.activateHotkey = HotkeyBinding(
            mods: ["shift", "ctrl", "cmd"], key: "f")
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("abc"),
            activateHotkeyOverride: HotkeyBinding(
                mods: ["alt"], key: "g"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": e],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains(
            "hs.hotkey.bind({ \"alt\" }, \"g\""))
        // Manifest default never appears.
        #expect(!snippet.contains(
            "hs.hotkey.bind({ \"shift\", \"ctrl\", \"cmd\" }, \"f\""))
    }

    @Test
    func activateHotkeyPausedSpoonStartsInactive() {
        // When state.paused is true, mstActive should initialise to
        // false so the next chord press starts the Spoon rather than
        // shouting "OFF" at it.
        var e = entry("MouseScrollTweaks",
                      hasConfigure: true, hasStart: true,
                      hotkeyActions: [])
        e.activateHotkey = HotkeyBinding(
            mods: ["shift", "ctrl", "cmd"], key: "s")
        var state = AppState()
        state.spoons["MouseScrollTweaks"] = SpoonState(
            sourceID: "catokolas", enabled: true, paused: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["MouseScrollTweaks": e],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        #expect(snippet.contains("mstActive[\"MouseScrollTweaks\"] = false"))
        // Also: no `start = true` for paused Spoons.
        let andUseRange = snippet.range(of: ":andUse(\"MouseScrollTweaks\"")!
        let afterAndUse = snippet[andUseRange.lowerBound...]
        let andUseEnd = afterAndUse.range(of: "})")!.upperBound
        let andUseBody = afterAndUse[..<andUseEnd]
        #expect(!andUseBody.contains("start = true"))
    }

    @Test
    func snippetWithoutActivateHotkeyOmitsHelpers() {
        // MoveSpaces (no activateHotkey, but has hotkeys[]) should NOT
        // get an activate-hotkey block or the deferred override loader.
        let e = entry("MoveSpaces",
                      hasConfigure: false, hasStart: false,
                      hotkeyDefaults: [
                        ("space_left", HotkeyBinding(
                            mods: ["shift", "ctrl"], key: "left")),
                        ("space_right", HotkeyBinding(
                            mods: ["shift", "ctrl"], key: "right"))])
        var state = AppState()
        state.spoons["MoveSpaces"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("abc"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["MoveSpaces": e],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        // MoveSpaces gets its per-action hotkeys via andUse.
        #expect(snippet.contains("hotkeys = { space_left"))
        // But no activate-hotkey block.
        #expect(!snippet.contains("-- Activate hotkey:"))
        // Helpers are unconditional (one block at the top) — they're
        // emitted but harmless when no Spoon uses them.
        #expect(snippet.contains("mstAlertStyle"))
    }

    @Test
    func spoonsAreSortedByName() {
        // Stable diffs when the user enables/disables Spoons in any
        // order. Output ordering must come from name sort, not state
        // iteration order.
        let entryA = entry("Alpha", hasConfigure: true, hasStart: true,
                           hotkeyActions: [])
        let entryZ = entry("Zebra", hasConfigure: true, hasStart: true,
                           hotkeyActions: [])
        var state = AppState()
        state.spoons["Zebra"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("z"))
        state.spoons["Alpha"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("a"))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["Alpha": entryA, "Zebra": entryZ],
            repos: ["catokolas": catokolasRepo],
            timestamp: fixedDate)
        let alphaIdx = snippet.range(of: ":andUse(\"Alpha\"")!.lowerBound
        let zebraIdx = snippet.range(of: ":andUse(\"Zebra\"")!.lowerBound
        #expect(alphaIdx < zebraIdx)
    }

    @Test
    func multipleSourcesRegisterOnlyTheCustomOnes() {
        // Mix of catokolas Spoons and upstream Spoons — only catokolas
        // gets a `repos[...]` registration line.
        let ffm = entry("FocusFollowsMouse",
                        hasConfigure: true, hasStart: true,
                        hotkeyActions: ["toggle"])
        let caf = entry("Caffeine",
                        hasConfigure: false, hasStart: true,
                        hotkeyActions: [])
        var state = AppState()
        state.spoons["FocusFollowsMouse"] = SpoonState(
            sourceID: "catokolas", enabled: true,
            installedRef: .gitCommit("a"))
        state.spoons["Caffeine"] = SpoonState(
            sourceID: "hammerspoon-official", enabled: true,
            installedRef: .zipETag(value: "etag", fetchedAt: fixedDate))
        let snippet = SnippetGenerator.generate(
            state: state,
            catalog: ["FocusFollowsMouse": ffm, "Caffeine": caf],
            repos: [
                "catokolas":            catokolasRepo,
                "hammerspoon-official": .default,
            ],
            timestamp: fixedDate)
        // Exactly one repo registration line.
        let repoLines = snippet.components(separatedBy: "\n")
            .filter { $0.contains("spoon.SpoonInstall.repos[") }
        #expect(repoLines.count == 1)
        #expect(repoLines[0].contains("\"catokolas\""))
    }

    // MARK: - Helpers

    private let catokolasRepo: RepoRef = .custom(
        id: "catokolas",
        url: "https://github.com/catokolas/HS_SpoonsContrib",
        branch: "main",
        desc: "Cato Kolås's contributed Spoons")

    private func entry(
        _ name: String,
        hasConfigure: Bool = true,
        hasStart: Bool = true,
        hotkeyActions: [String] = []
    ) -> SpoonCatalogEntry {
        return SpoonCatalogEntry(
            id: "test:\(name)",
            name: name,
            sourceID: "catokolas",
            metadata: SpoonMetadata(version: "0.1", description: nil,
                                    author: nil, homepage: nil, license: nil),
            lifecycle: Lifecycle(
                hasStart: hasStart, hasStop: true, hasToggle: false,
                hasConfigure: hasConfigure, eventDriven: false),
            config: [],
            hotkeys: hotkeyActions.map { action in
                HotkeyAction(action: action, label: nil, default: nil)
            },
            provenance: .manifest)
    }

    /// Variant that lets tests give actions an authored `default`.
    /// Used by the manifest-default fallback tests; the no-default
    /// helper above stays minimal for older tests. Different argument
    /// label so neither overload becomes ambiguous when the caller
    /// omits `hotkeyActions`.
    private func entry(
        _ name: String,
        hasConfigure: Bool = true,
        hasStart: Bool = true,
        hotkeyDefaults: [(String, HotkeyBinding?)]
    ) -> SpoonCatalogEntry {
        return SpoonCatalogEntry(
            id: "test:\(name)",
            name: name,
            sourceID: "catokolas",
            metadata: SpoonMetadata(version: "0.1", description: nil,
                                    author: nil, homepage: nil, license: nil),
            lifecycle: Lifecycle(
                hasStart: hasStart, hasStop: true, hasToggle: false,
                hasConfigure: hasConfigure, eventDriven: false),
            config: [],
            hotkeys: hotkeyDefaults.map { (action, def) in
                HotkeyAction(action: action, label: nil, default: def)
            },
            provenance: .manifest)
    }
}
