import Foundation

/// Generates `~/.hammerspoon/mac_spoons_tweaks.lua` — the managed file
/// the app writes and `~/.hammerspoon/init.lua` `require`s.
///
/// One `spoon.SpoonInstall:andUse(...)` block per enabled+installed
/// Spoon. SpoonInstall handles install-if-missing, load, configure,
/// hotkey-bind, and start in a single declarative call; we just have
/// to give it the right options table.
///
/// `andUse` wraps each Spoon's load in xpcall internally, so one
/// breakage doesn't take out the rest of init — matches the plan's
/// "per-Spoon failure isolation" requirement without us re-implementing
/// `pcall` wrappers here.
public enum SnippetGenerator {

    /// Stable header line used by `InitLuaPatcher` to recognize this is
    /// a managed file and (eventually) by a future migration tool that
    /// might rewrite older snippet versions.
    public static let managedMarker =
        "-- mac_spoons_tweaks.lua — MANAGED FILE — DO NOT EDIT."

    /// Build the snippet.
    ///
    /// - Parameters:
    ///   - state: persisted user state (which Spoons are enabled, with
    ///     what configs and hotkeys).
    ///   - catalog: map from Spoon name → catalog entry (for lifecycle:
    ///     hasConfigure, hasStart, eventDriven). A Spoon in `state` that
    ///     is not in `catalog` is skipped (defensive: drift between
    ///     state.json and catalog should not produce broken Lua).
    ///   - repos: map from sourceID → `RepoRef` describing how to
    ///     register that source with SpoonInstall. `default` entries
    ///     are skipped automatically (SpoonInstall ships with it).
    ///   - timestamp: capture time for the header comment. Pass an
    ///     explicit value in tests for stable snapshots.
    public static func generate(
        state: AppState,
        catalog: [String: SpoonCatalogEntry],
        repos: [String: RepoRef],
        timestamp: Date = Date()
    ) -> String {
        var out: [String] = []
        out.append(managedMarker)
        out.append("-- Generated by MacSpoonsTweaks at \(iso8601(timestamp)).")
        out.append("-- To stop the app managing your Spoons, delete this file AND remove")
        out.append("-- the `require(\"mac_spoons_tweaks\")` line from init.lua.")
        out.append("")
        // Open the Mach message port the `hs` CLI talks to. Without
        // this, the app's bridge calls fail with "can't access
        // Hammerspoon message port" — so apply/install can't push live
        // changes until Hammerspoon is reloaded.
        out.append("require(\"hs.ipc\")")
        out.append("hs.loadSpoon(\"SpoonInstall\")")
        // SpoonInstall.spoon was deleted / never installed — bail with a
        // clear hint instead of letting line N nil-index trap.
        out.append("if not spoon.SpoonInstall then")
        out.append("  hs.alert.show(\"MacSpoonsTweaks: SpoonInstall.spoon is missing — open the app to reinstall.\", 10)")
        out.append("  return")
        out.append("end")
        out.append("spoon.SpoonInstall.use_syncinstall = false")
        out.append("")

        // Activate-hotkey support: alert style + on/off-state table +
        // override-file helpers. Emit once near the top; per-Spoon
        // `hs.hotkey.bind` blocks below close over these.
        out.append(activateHotkeyHelpers)
        out.append("")

        // Filter to Spoons we'll actually emit so the repo-registration
        // section only covers sources that have a live entry below.
        // We emit `andUse` for every enabled Spoon regardless of
        // installedRef — SpoonInstall:andUse install-if-missing handles
        // the not-installed case on Hammerspoon start, and the install
        // path through SpoonInstaller is decoupled from Apply. Filtering
        // on installedRef would mean a user's config edits silently
        // dropped out of the snippet between Apply and a not-yet-run
        // SpoonInstaller. Defensive: still drop entries the catalog
        // doesn't have so we never produce broken Lua.
        let emittable = state.spoons
            .filter { (_, s) in s.enabled }
            .compactMap { (name, s) -> (String, SpoonState, SpoonCatalogEntry)? in
                guard let entry = catalog[name] else { return nil }
                return (name, s, entry)
            }
            .sorted { $0.0 < $1.0 }   // stable diffs

        // Repo registrations: one per unique custom sourceID actually used.
        let usedSources = Set(emittable.map { $0.1.sourceID })
        let registrations = usedSources
            .sorted()
            .compactMap { sourceID -> String? in
                guard let repo = repos[sourceID], case .custom = repo else {
                    return nil
                }
                return SpoonInstallScript.registerRepo(
                    id: repo.id, url: customURL(repo), branch: customBranch(repo),
                    desc: customDesc(repo))
            }
        if !registrations.isEmpty {
            out.append("-- Custom repos (the official one is built in as \"default\")")
            out.append(contentsOf: registrations)
            out.append("")
        }

        if emittable.isEmpty {
            out.append("-- No Spoons enabled.")
            return out.joined(separator: "\n") + "\n"
        }

        for (name, s, entry) in emittable {
            out.append(renderAndUse(
                name: name, state: s, entry: entry, repos: repos))
            out.append("")
        }

        // Activate-hotkey bind blocks for the Spoons that carry an
        // `activateHotkey` in the manifest (or a user override). Grouped
        // after every `andUse` block so the `spoon.X` global definitely
        // exists by the time the bind body runs.
        let withActivate = emittable.filter { _, s, entry in
            resolvedActivateHotkey(state: s, entry: entry) != nil
        }
        if !withActivate.isEmpty {
            out.append("-- Activate hotkeys (toggle Spoon on/off + persist + alert)")
            for (name, s, entry) in withActivate {
                if let chord = resolvedActivateHotkey(state: s, entry: entry) {
                    out.append(renderActivateHotkey(
                        name: name, chord: chord, paused: s.paused))
                    out.append("")
                }
            }
        }

        // Apply chord-driven runtime overrides after all `andUse` blocks
        // have had a chance to bring the Spoon instances into existence.
        // `hs.timer.doAfter` defers past the synchronous load phase
        // without us having to reason about andUse's async install path.
        if !withActivate.isEmpty {
            out.append(applyRuntimeOverridesBlock)
            out.append("")
        }

        return out.joined(separator: "\n")
    }

    // MARK: - Internals

    private static func renderAndUse(
        name: String, state: SpoonState, entry: SpoonCatalogEntry,
        repos: [String: RepoRef]
    ) -> String {
        var fields: [String] = []
        // Translate sourceID → the actual SpoonInstall repo name. For
        // "hammerspoon-official" that's "default" (built into
        // SpoonInstall); for "catokolas" it's "catokolas" (which we
        // registered above). Without the translation, andUse can't
        // resolve the repo for upstream Spoons and silently skips the
        // hotkey/start wiring.
        let repoName = repos[state.sourceID]?.id ?? state.sourceID
        fields.append("  repo = \(LuaLiteral.encodeString(repoName)),")

        // Config branch: nested-merge `fn` for Spoons with :configure;
        // flat `config` for upstream Spoons that lack it.
        if !state.config.isEmpty {
            let table = LuaLiteral.encodeTable(state.config)
            if entry.lifecycle.hasConfigure {
                fields.append(
                    "  fn = function(s) s:configure(\(table)) end,")
            } else {
                fields.append("  config = \(table),")
            }
        }

        // Resolve hotkeys at render time so a Spoon with manifest
        // defaults still gets a `hotkeys = …` block when the user
        // hasn't recorded any overrides. User overrides win per-action.
        // SKIPPED when the Spoon has an `activateHotkey` — those chords
        // are bound separately below via our own `hs.hotkey.bind` (so
        // we can run start/stop, persist, and show an alert in the
        // callback, none of which SpoonInstall's per-action wiring
        // supports).
        if entry.activateHotkey == nil
            && state.activateHotkeyOverride == nil {
            let resolvedHotkeys = HotkeyAction.resolved(
                state: state.hotkeys, manifest: entry.hotkeys)
            if !resolvedHotkeys.isEmpty {
                fields.append("  hotkeys = \(encodeHotkeys(resolvedHotkeys)),")
            }
        }

        // Omit `start = true` for paused Spoons. The `andUse` block
        // still loads + configures + binds hotkeys so resuming is just
        // an `:start()` call away; reload from cold leaves it dormant.
        if entry.lifecycle.hasStart && !state.paused {
            fields.append("  start = true,")
        }

        return "spoon.SpoonInstall:andUse(\(LuaLiteral.encodeString(name)), {\n" +
               fields.joined(separator: "\n") +
               "\n})"
    }

    /// Hotkey table form: `{ action = { {"mod1","mod2"}, "key" }, … }`.
    /// Lua's `hs.hotkey.bindSpec` wants the binding as a 2-element
    /// sequence (mods list, then key string), which doesn't map onto
    /// `ConfigValue` cleanly — so we render it directly here.
    private static func encodeHotkeys(
        _ mapping: [String: HotkeyBinding]
    ) -> String {
        if mapping.isEmpty { return "{}" }
        let entries = mapping.keys.sorted().map { action -> String in
            let b = mapping[action]!
            let modsList = LuaLiteral.encode(.stringList(b.mods))
            let key      = LuaLiteral.encodeString(b.key)
            return "\(LuaLiteral.encodeKey(action)) = { \(modsList), \(key) }"
        }
        return "{ " + entries.joined(separator: ", ") + " }"
    }

    // MARK: - Activate hotkey

    /// User override (state) wins; manifest default is the fallback.
    /// Nil for Spoons that ship no activate chord (MoveSpaces,
    /// SpotifyPlayPause) and have no user override either.
    private static func resolvedActivateHotkey(
        state: SpoonState, entry: SpoonCatalogEntry
    ) -> HotkeyBinding? {
        return state.activateHotkeyOverride ?? entry.activateHotkey
    }

    /// `do … end` block: closure-local initial-active flag (mirrors
    /// `start = true` minus paused), a `hs.hotkey.bind` whose callback
    /// flips the flag, calls `:start`/`:stop` on the Spoon, persists
    /// the new state to the override file via `mstSetOverride`, and
    /// flashes an `hs.alert`.
    private static func renderActivateHotkey(
        name: String, chord: HotkeyBinding, paused: Bool
    ) -> String {
        let mods = LuaLiteral.encode(.stringList(chord.mods))
        let key  = LuaLiteral.encodeString(chord.key)
        let initial = paused ? "false" : "true"
        var lines: [String] = []
        lines.append("-- Activate hotkey: \(name)")
        lines.append("do")
        lines.append("  mstActive[\(LuaLiteral.encodeString(name))] = \(initial)")
        lines.append("  hs.hotkey.bind(\(mods), \(key), function()")
        lines.append("    local n = \(LuaLiteral.encodeString(name))")
        lines.append("    mstActive[n] = not mstActive[n]")
        lines.append("    if mstActive[n] then")
        lines.append("      if spoon[n] and spoon[n].start then pcall(function() spoon[n]:start() end) end")
        lines.append("      mstSetOverride(n, false)")
        lines.append("      hs.alert.show(n .. \": ON\", mstAlertStyle, 1.0)")
        lines.append("    else")
        lines.append("      if spoon[n] and spoon[n].stop  then pcall(function() spoon[n]:stop()  end) end")
        lines.append("      mstSetOverride(n, true)")
        lines.append("      hs.alert.show(n .. \": OFF\", mstAlertStyle, 1.0)")
        lines.append("    end")
        lines.append("  end)")
        lines.append("end")
        return lines.joined(separator: "\n")
    }

    /// Helpers block emitted once near the top of the snippet. Defines
    /// the shared alert style, the `mstActive` flag table, and the
    /// override-file read/write helpers used by every activate-hotkey
    /// callback.
    private static let activateHotkeyHelpers: String = """
    -- MacSpoonsTweaks: activate-hotkey helpers (alert + persistence)
    local mstAlertStyle = {
      textSize = 24, textColor = { white = 1, alpha = 1 },
      fillColor = { white = 0.05, alpha = 0.85 },
      strokeWidth = 0, radius = 12, atScreenEdge = 0,
      fadeInDuration = 0.1, fadeOutDuration = 0.4,
    }
    local mstOverridesPath = (os.getenv("HOME") or "")
      .. "/.hammerspoon/mac_spoons_tweaks_overrides.lua"
    mstActive = mstActive or {}
    local function mstReadOverrides()
      local ok, t = pcall(dofile, mstOverridesPath)
      if ok and type(t) == "table" then return t end
      return {}
    end
    local function mstSetOverride(name, deactivated)
      local t = mstReadOverrides()
      if deactivated then t[name] = true else t[name] = nil end
      local names = {}
      for k in pairs(t) do names[#names+1] = k end
      table.sort(names)
      local f = io.open(mstOverridesPath, "w")
      if not f then return end
      f:write("-- mac_spoons_tweaks_overrides.lua - MANAGED FILE - DO NOT EDIT.\\n")
      f:write("return {\\n")
      for _, n in ipairs(names) do f:write("  " .. n .. " = true,\\n") end
      f:write("}\\n")
      f:close()
    end
    """

    /// Runs after every `andUse` (deferred via `hs.timer.doAfter` to
    /// clear SpoonInstall's async install/load phase). For every Spoon
    /// listed in the override file, flips `mstActive` to false and
    /// calls `:stop()` so chord-induced deactivations survive
    /// `hs.reload()`.
    private static let applyRuntimeOverridesBlock: String = """
    -- Apply chord-driven runtime overrides (deactivations that survived
    -- hs.reload()). Deferred so SpoonInstall finishes loading the
    -- Spoons before we try to call :stop() on them.
    hs.timer.doAfter(0.5, function()
      local ok, t = pcall(dofile, (os.getenv("HOME") or "")
        .. "/.hammerspoon/mac_spoons_tweaks_overrides.lua")
      if not (ok and type(t) == "table") then return end
      for name in pairs(t) do
        if spoon[name] and spoon[name].stop then
          pcall(function() spoon[name]:stop() end)
        end
        mstActive[name] = false
      end
    end)
    """

    // MARK: - Misc

    private static func iso8601(_ d: Date) -> String {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f.string(from: d)
    }

    // Tiny helpers to pull the RepoRef.custom fields out without each
    // call site having to switch on the enum.
    private static func customURL(_ r: RepoRef) -> String {
        if case .custom(_, let url, _, _) = r { return url }
        return ""
    }
    private static func customBranch(_ r: RepoRef) -> String {
        if case .custom(_, _, let branch, _) = r { return branch }
        return ""
    }
    private static func customDesc(_ r: RepoRef) -> String? {
        if case .custom(_, _, _, let desc) = r { return desc }
        return nil
    }
}
