import Foundation

/// Generates `~/.hammerspoon/mac_spoons_tweaks.lua` — the managed file
/// the app writes and `~/.hammerspoon/init.lua` `require`s.
///
/// One `spoon.SpoonInstall:andUse(...)` block per enabled+installed
/// Spoon. SpoonInstall handles install-if-missing, load, configure,
/// hotkey-bind, and start in a single declarative call; we just have
/// to give it the right options table.
///
/// `andUse` wraps each Spoon's load in xpcall internally, so one
/// breakage doesn't take out the rest of init — matches the plan's
/// "per-Spoon failure isolation" requirement without us re-implementing
/// `pcall` wrappers here.
public enum SnippetGenerator {

    /// Stable header line used by `InitLuaPatcher` to recognize this is
    /// a managed file and (eventually) by a future migration tool that
    /// might rewrite older snippet versions.
    public static let managedMarker =
        "-- mac_spoons_tweaks.lua — MANAGED FILE — DO NOT EDIT."

    /// Build the snippet.
    ///
    /// - Parameters:
    ///   - state: persisted user state (which Spoons are enabled, with
    ///     what configs and hotkeys).
    ///   - catalog: map from Spoon name → catalog entry (for lifecycle:
    ///     hasConfigure, hasStart, eventDriven). A Spoon in `state` that
    ///     is not in `catalog` is skipped (defensive: drift between
    ///     state.json and catalog should not produce broken Lua).
    ///   - repos: map from sourceID → `RepoRef` describing how to
    ///     register that source with SpoonInstall. `default` entries
    ///     are skipped automatically (SpoonInstall ships with it).
    ///   - timestamp: capture time for the header comment. Pass an
    ///     explicit value in tests for stable snapshots.
    public static func generate(
        state: AppState,
        catalog: [String: SpoonCatalogEntry],
        repos: [String: RepoRef],
        timestamp: Date = Date()
    ) -> String {
        var out: [String] = []
        out.append(managedMarker)
        out.append("-- Generated by MacSpoonsTweaks at \(iso8601(timestamp)).")
        out.append("-- To stop the app managing your Spoons, delete this file AND remove")
        out.append("-- the `require(\"mac_spoons_tweaks\")` line from init.lua.")
        out.append("")
        out.append("hs.loadSpoon(\"SpoonInstall\")")
        out.append("spoon.SpoonInstall.use_syncinstall = false")
        out.append("")

        // Filter to Spoons we'll actually emit so the repo-registration
        // section only covers sources that have a live entry below.
        // We emit `andUse` for every enabled Spoon regardless of
        // installedRef — SpoonInstall:andUse install-if-missing handles
        // the not-installed case on Hammerspoon start, and the install
        // path through SpoonInstaller is decoupled from Apply. Filtering
        // on installedRef would mean a user's config edits silently
        // dropped out of the snippet between Apply and a not-yet-run
        // SpoonInstaller. Defensive: still drop entries the catalog
        // doesn't have so we never produce broken Lua.
        let emittable = state.spoons
            .filter { (_, s) in s.enabled }
            .compactMap { (name, s) -> (String, SpoonState, SpoonCatalogEntry)? in
                guard let entry = catalog[name] else { return nil }
                return (name, s, entry)
            }
            .sorted { $0.0 < $1.0 }   // stable diffs

        // Repo registrations: one per unique custom sourceID actually used.
        let usedSources = Set(emittable.map { $0.1.sourceID })
        let registrations = usedSources
            .sorted()
            .compactMap { sourceID -> String? in
                guard let repo = repos[sourceID], case .custom = repo else {
                    return nil
                }
                return SpoonInstallScript.registerRepo(
                    id: repo.id, url: customURL(repo), branch: customBranch(repo),
                    desc: customDesc(repo))
            }
        if !registrations.isEmpty {
            out.append("-- Custom repos (the official one is built in as \"default\")")
            out.append(contentsOf: registrations)
            out.append("")
        }

        if emittable.isEmpty {
            out.append("-- No Spoons enabled.")
            return out.joined(separator: "\n") + "\n"
        }

        for (name, s, entry) in emittable {
            out.append(renderAndUse(name: name, state: s, entry: entry))
            out.append("")
        }

        return out.joined(separator: "\n")
    }

    // MARK: - Internals

    private static func renderAndUse(
        name: String, state: SpoonState, entry: SpoonCatalogEntry
    ) -> String {
        var fields: [String] = []
        fields.append("  repo = \(LuaLiteral.encodeString(state.sourceID)),")

        // Config branch: nested-merge `fn` for Spoons with :configure;
        // flat `config` for upstream Spoons that lack it.
        if !state.config.isEmpty {
            let table = LuaLiteral.encodeTable(state.config)
            if entry.lifecycle.hasConfigure {
                fields.append(
                    "  fn = function(s) s:configure(\(table)) end,")
            } else {
                fields.append("  config = \(table),")
            }
        }

        if !state.hotkeys.isEmpty {
            fields.append("  hotkeys = \(encodeHotkeys(state.hotkeys)),")
        }

        if entry.lifecycle.hasStart {
            fields.append("  start = true,")
        }

        return "spoon.SpoonInstall:andUse(\(LuaLiteral.encodeString(name)), {\n" +
               fields.joined(separator: "\n") +
               "\n})"
    }

    /// Hotkey table form: `{ action = { {"mod1","mod2"}, "key" }, … }`.
    /// Lua's `hs.hotkey.bindSpec` wants the binding as a 2-element
    /// sequence (mods list, then key string), which doesn't map onto
    /// `ConfigValue` cleanly — so we render it directly here.
    private static func encodeHotkeys(
        _ mapping: [String: HotkeyBinding]
    ) -> String {
        if mapping.isEmpty { return "{}" }
        let entries = mapping.keys.sorted().map { action -> String in
            let b = mapping[action]!
            let modsList = LuaLiteral.encode(.stringList(b.mods))
            let key      = LuaLiteral.encodeString(b.key)
            return "\(LuaLiteral.encodeKey(action)) = { \(modsList), \(key) }"
        }
        return "{ " + entries.joined(separator: ", ") + " }"
    }

    private static func iso8601(_ d: Date) -> String {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f.string(from: d)
    }

    // Tiny helpers to pull the RepoRef.custom fields out without each
    // call site having to switch on the enum.
    private static func customURL(_ r: RepoRef) -> String {
        if case .custom(_, let url, _, _) = r { return url }
        return ""
    }
    private static func customBranch(_ r: RepoRef) -> String {
        if case .custom(_, _, let branch, _) = r { return branch }
        return ""
    }
    private static func customDesc(_ r: RepoRef) -> String? {
        if case .custom(_, _, _, let desc) = r { return desc }
        return nil
    }
}
