import Foundation

/// Orchestrates the Apply workflow: persist to `state.json`, regenerate
/// `~/.hammerspoon/mac_spoons_tweaks.lua`, and push the live
/// `:configure` / `:bindHotkeys` calls via the bridge.
///
/// Three layers that the rest of the kit already provides — this is
/// the seam where the SwiftUI Apply button finally does something.
public final class SpoonOrchestrator: @unchecked Sendable {

    public let store:       StateStore
    public let runner:      any LuaRunner
    public let snippetPath: URL

    /// Closure that returns the latest in-memory catalog (name → entry).
    /// Wrapped in a closure rather than a static map because the
    /// catalog can be refreshed independently of the orchestrator.
    public let catalogProvider: @Sendable () -> [String: SpoonCatalogEntry]

    /// Closure that returns the active `RepoRef` for each sourceID
    /// referenced by enabled Spoons in state.json.
    public let reposProvider: @Sendable () -> [String: RepoRef]

    /// Source of "now" for the snippet's `Generated by …` header. Tests
    /// inject a fixed value for stable diffs.
    public let clock: @Sendable () -> Date

    public init(
        store:       StateStore,
        runner:      any LuaRunner,
        snippetPath: URL,
        catalogProvider: @escaping @Sendable () -> [String: SpoonCatalogEntry],
        reposProvider:   @escaping @Sendable () -> [String: RepoRef],
        clock:           @escaping @Sendable () -> Date = { Date() }
    ) {
        self.store           = store
        self.runner          = runner
        self.snippetPath     = snippetPath
        self.catalogProvider = catalogProvider
        self.reposProvider   = reposProvider
        self.clock           = clock
    }

    // MARK: - Seed

    /// Read the current overrides for a Spoon out of `state.json`. The
    /// UI seeds its `@State values` and `@State hotkeyOverrides` from
    /// this so re-opening a Spoon's detail panel shows previously
    /// saved edits.
    public func seedState(
        for name: String
    ) -> (config: [String: ConfigValue],
          hotkeys: [String: HotkeyBinding]) {
        let state = (try? store.load()) ?? AppState()
        let spoon = state.spoons[name]
        return (
            config:  spoon?.config  ?? [:],
            hotkeys: spoon?.hotkeys ?? [:])
    }

    // MARK: - Apply

    public enum ApplyError: Error, CustomStringConvertible {
        case persistFailed(any Error)
        case snippetWriteFailed(any Error)

        public var description: String {
            switch self {
            case .persistFailed(let e):
                return "Failed to save state.json: \(e)"
            case .snippetWriteFailed(let e):
                return "Failed to write mac_spoons_tweaks.lua: \(e)"
            }
        }
    }

    public struct ApplyResult: Sendable {
        /// The snippet file we wrote.
        public let snippetPath: URL
        /// `true` if the live `:configure` + `:bindHotkeys` succeeded.
        /// `false` means persistence happened but the user has to
        /// reload Hammerspoon to pick up the new config — e.g. the
        /// CLI isn't installed, or Hammerspoon isn't running.
        public let liveAppliedOK: Bool
        /// Stringified error from the live-apply attempt, if any.
        public let liveApplyError: String?
    }

    /// Persist, regenerate, and push live. Persistence and snippet
    /// regeneration are required (throw on failure); the live-apply
    /// step is best-effort and surfaced via the returned result.
    @discardableResult
    public func apply(
        entry: SpoonCatalogEntry,
        values: [String: ConfigValue],
        hotkeyOverrides: [String: HotkeyBinding]
    ) async throws -> ApplyResult {

        // 1. Persist the new state for THIS Spoon. Preserve other
        //    Spoons' state and this Spoon's existing
        //    sourceID/enabled/installedRef.
        let newSpoonState = SpoonState(
            sourceID:     entry.sourceID,
            enabled:      true,                  // implicit enable on Apply
            installedRef: nil,                   // ←— set by SpoonInstaller
            config:       values,
            hotkeys:      hotkeyOverrides)

        do {
            try store.update { state in
                if let existing = state.spoons[entry.name] {
                    var merged = newSpoonState
                    merged.installedRef        = existing.installedRef
                    merged.installedSchemaKeys = existing.installedSchemaKeys
                    merged.enabled             = existing.enabled || true
                    state.spoons[entry.name] = merged
                } else {
                    state.spoons[entry.name] = newSpoonState
                }
            }
        } catch {
            throw ApplyError.persistFailed(error)
        }

        // 2. Regenerate the managed snippet.
        do {
            let state = try store.load()
            let snippet = SnippetGenerator.generate(
                state:     state,
                catalog:   catalogProvider(),
                repos:     reposProvider(),
                timestamp: clock())
            try writeSnippet(snippet)
        } catch {
            throw ApplyError.snippetWriteFailed(error)
        }

        // 3. Push live changes via the runner. Best-effort — a failure
        //    here doesn't roll back persistence; the user can fix the
        //    Hammerspoon situation and reload to pick up the snippet.
        var liveOK    = true
        var liveError: String? = nil

        // Ensure the Spoon is loaded before configuring or starting
        // it. First-time Apply between Install and Hammerspoon reload
        // otherwise fails with `attempt to index nil value (field 'X')`.
        // hs.loadSpoon is idempotent so this is cheap on subsequent
        // applies.
        let hasLiveWork = !values.isEmpty
            || !hotkeyOverrides.isEmpty
            || entry.lifecycle.hasStart
        if hasLiveWork {
            do {
                _ = try await runner.runLua(
                    HammerspoonScript.loadSpoon(entry.name), timeout: 5)
            } catch {
                liveOK    = false
                liveError = String(describing: error)
            }
        }

        // Stop BEFORE re-configuring so a re-Apply with new config
        // doesn't leave the previous instance's event taps registered
        // alongside the new ones. Best-effort: if the Spoon was never
        // started (first Apply), `:stop()` may no-op or fail; we
        // proceed regardless.
        if entry.lifecycle.hasStart && entry.lifecycle.hasStop {
            _ = try? await runner.stopSpoon(entry.name)
        }

        if !values.isEmpty {
            do {
                try await runner.configure(
                    spoon:        entry.name,
                    config:       .object(values),
                    hasConfigure: entry.lifecycle.hasConfigure)
            } catch {
                liveOK    = false
                liveError = [liveError, String(describing: error)]
                    .compactMap { $0 }
                    .joined(separator: " | ")
            }
        }

        if !hotkeyOverrides.isEmpty {
            do {
                try await runner.bindHotkeys(
                    spoon:   entry.name,
                    mapping: hotkeyOverrides)
            } catch {
                liveOK    = false
                // Concatenate so the first failure isn't masked.
                liveError = [liveError, String(describing: error)]
                    .compactMap { $0 }
                    .joined(separator: " | ")
            }
        }

        // Mirror the snippet's `start = true` so an event-driven
        // Spoon (Spotify watcher, FocusFollowsMouse, etc.) actually
        // takes effect on Apply without needing a Hammerspoon reload.
        if entry.lifecycle.hasStart {
            do {
                try await runner.startSpoon(entry.name)
            } catch {
                liveOK    = false
                liveError = [liveError, String(describing: error)]
                    .compactMap { $0 }
                    .joined(separator: " | ")
            }
        }

        return ApplyResult(
            snippetPath:    snippetPath,
            liveAppliedOK:  liveOK,
            liveApplyError: liveError)
    }

    // MARK: - Pause / Resume

    /// Toggle a Spoon's `paused` flag. Same three-step shape as `apply`
    /// (persist → regenerate snippet → push live) so views can reuse
    /// the same status plumbing. Live step calls `:stop()` (pausing) or
    /// loadSpoon→`:start()` (resuming); the snippet still keeps the
    /// `:andUse` block so config / hotkeys / load survive a reload.
    @discardableResult
    public func setPaused(
        entry: SpoonCatalogEntry,
        paused: Bool
    ) async throws -> ApplyResult {

        // 1. Persist.
        do {
            try store.update { state in
                guard var s = state.spoons[entry.name] else {
                    // Pause request for a Spoon we have no state for —
                    // create a stub so the flag survives. enabled stays
                    // false; the caller is responsible for enabling.
                    state.spoons[entry.name] = SpoonState(
                        sourceID: entry.sourceID,
                        enabled:  false,
                        paused:   paused)
                    return
                }
                s.paused = paused
                state.spoons[entry.name] = s
            }
        } catch {
            throw ApplyError.persistFailed(error)
        }

        // 2. Regenerate the managed snippet.
        do {
            let state = try store.load()
            let snippet = SnippetGenerator.generate(
                state:     state,
                catalog:   catalogProvider(),
                repos:     reposProvider(),
                timestamp: clock())
            try writeSnippet(snippet)
        } catch {
            throw ApplyError.snippetWriteFailed(error)
        }

        // 3. Push live. Best-effort — failures surface in ApplyResult.
        var liveOK    = true
        var liveError: String? = nil

        if paused {
            // Stop the running instance. No need to loadSpoon first —
            // if it isn't loaded, there's nothing to stop, and `:stop()`
            // on a nil reference is benign-or-errors; we swallow the
            // error and report it.
            if entry.lifecycle.hasStop {
                do {
                    try await runner.stopSpoon(entry.name)
                } catch {
                    liveOK    = false
                    liveError = String(describing: error)
                }
            }
        } else {
            // Resume: mirror the apply path's loadSpoon → start.
            do {
                _ = try await runner.runLua(
                    HammerspoonScript.loadSpoon(entry.name), timeout: 5)
            } catch {
                liveOK    = false
                liveError = String(describing: error)
            }
            if entry.lifecycle.hasStart {
                do {
                    try await runner.startSpoon(entry.name)
                } catch {
                    liveOK    = false
                    liveError = [liveError, String(describing: error)]
                        .compactMap { $0 }
                        .joined(separator: " | ")
                }
            }
        }

        return ApplyResult(
            snippetPath:    snippetPath,
            liveAppliedOK:  liveOK,
            liveApplyError: liveError)
    }

    // MARK: - Internals

    private func writeSnippet(_ snippet: String) throws {
        try FileManager.default.createDirectory(
            at: snippetPath.deletingLastPathComponent(),
            withIntermediateDirectories: true)
        try snippet.write(to: snippetPath, atomically: true, encoding: .utf8)
    }
}
